version: "3.5"
services:
  api1: &api
    build: .
    hostname: api01
    networks:
      - rinha-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      HTTP_PORT: 3000
      POOL_SIZE: 10
      DB_HOST: database
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "125MB"

  api2:
    <<: *api
    hostname: api02
    healthcheck:
      test: curl --fail http://localhost:3001/ || exit 1
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      HTTP_PORT: 3001
      POOL_SIZE: 10
      DB_HOST: database

  nginx: # Load Balancer
    image: nginx:latest
    networks:
      - rinha-network
    ports:
      - 9999:9999
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  db: # Banco de dados
    image: postgres:15
    hostname: database
    volumes:
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./configs/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    networks:
      - rinha-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinha_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "250MB"

networks:
  rinha-network:
    driver: bridge
